# -*- coding: utf-8 -*-
"""q and A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iyrgjOWEB_xN6d3zCPLTMfTIeCDFZdB_
"""

!pip install transformers sentence-transformers gradio --quiet

from transformers import pipeline
from sentence_transformers import SentenceTransformer, util
import torch
import gradio as gr

qa_pipeline = pipeline("question-answering", model="distilbert-base-uncased-distilled-squad")
embedder = SentenceTransformer('all-MiniLM-L6-v2')

#  RAW KNOWLEDGE BASE: Manually entered (split by two newlines)
raw_knowledge = """
The mitochondria is the powerhouse of the cell. It produces ATP through cellular respiration.

Newton's third law states that for every action, there is an equal and opposite reaction.

The Great Wall of China is one of the most famous architectural feats in history.

Water boils at 100 degrees Celsius under normal atmospheric pressure.

Romeo and Juliet is a tragedy written by William Shakespeare.

Photosynthesis allows plants to convert sunlight, water, and carbon dioxide into glucose and oxygen.

The speed of light in a vacuum is approximately 299,792 kilometers per second.

Albert Einstein developed the theory of relativity in the early 20th century.

The Taj Mahal is a UNESCO World Heritage Site located in Agra, India.

Mount Everest is the highest mountain above sea level, standing at 8,848 meters.

Python is a high-level, interpreted programming language known for its simplicity.

Java is an object-oriented programming language that runs on the Java Virtual Machine.

HTML stands for HyperText Markup Language and is used to create webpages.

CSS stands for Cascading Style Sheets and is used to style HTML content.

The periodic table organizes elements based on their atomic number and properties.

Water is made up of two hydrogen atoms and one oxygen atom — H2O.

The Amazon rainforest is the largest tropical rainforest in the world.

Shakespeare also wrote plays like Macbeth, Othello, and King Lear.

Venus is the hottest planet in our solar system due to its thick atmosphere.

Neil Armstrong was the first person to walk on the moon in 1969.

Jupiter is the largest planet in the solar system.

Isaac Newton formulated the laws of motion and universal gravitation.

The Eiffel Tower is located in Paris, France.

The brain is the control center of the human nervous system.

The heart pumps blood throughout the human body.

Mahatma Gandhi led India to independence through nonviolent civil disobedience.

The Pacific Ocean is the largest ocean on Earth.

Light travels faster than sound.

Sound requires a medium to travel, unlike light.

Electricity is the flow of electrons through a conductor.

Magnetism is a force that can attract or repel certain materials.

A black hole is a region of space with a gravitational field so strong that nothing can escape it.

The Sun is a star at the center of our solar system.

Saturn is famous for its beautiful rings made of ice and rock.

A leap year has 366 days, occurring every 4 years.

An ecosystem consists of all the living and nonliving things in an area.

Carbon dioxide is a gas that plants use during photosynthesis.

The respiratory system allows us to breathe and exchange gases.

The digestive system breaks down food into nutrients.

A noun is a word used to name a person, place, thing, or idea.

An adjective describes a noun.

The Pythagorean theorem states that a² + b² = c² in a right triangle.

A prime number is a number greater than 1 with only two factors: 1 and itself.

World War I began in 1914 and ended in 1918.

World War II lasted from 1939 to 1945.

The United Nations was founded in 1945 to promote peace and cooperation.

Water freezes at 0 degrees Celsius.

The moon orbits the Earth approximately every 27.3 days.

There are 206 bones in the adult human body.

DNA carries genetic information in living organisms.

Cells are the basic structural and functional units of life.

The Internet is a global network that connects computers worldwide.

Photosynthesis produces oxygen as a byproduct.

Rainbows form when sunlight is refracted and reflected in water droplets.

Friction is a force that opposes motion between two surfaces.

The lungs are the primary organs for breathing.

The pancreas produces insulin to help regulate blood sugar levels.

The liver detoxifies chemicals and metabolizes drugs in the body.

A galaxy is a massive system of stars, gas, and dust bound together by gravity.

The Milky Way is the galaxy that contains our solar system.

The Statue of Liberty was a gift from France to the United States.

Pluto was reclassified from a planet to a dwarf planet in 2006.

The Renaissance was a period of cultural revival in Europe during the 14th to 17th centuries.

A democracy is a system of government by the people.

The Berlin Wall fell in 1989, symbolizing the end of the Cold War.

The lungs exchange oxygen and carbon dioxide during breathing.

The Sahara is the largest hot desert in the world.

The Antarctic is the coldest continent on Earth.

Gravity is a force that attracts objects toward each other.

Vaccines help prevent the spread of infectious diseases.

Antibiotics are used to treat bacterial infections.

India is the world's largest democracy.

The national animal of India is the Bengal tiger.

The longest river in the world is the Nile.

The pancreas helps in digestion and regulation of blood sugar.

Respiration is the process of releasing energy from food.

The water cycle includes evaporation, condensation, precipitation, and collection.

Photosynthesis occurs in the chloroplasts of plant cells.

The Earth revolves around the Sun once every 365.25 days.

An eclipse occurs when one celestial body blocks another.

Mars is known as the Red Planet.

C++ is a general-purpose programming language created by Bjarne Stroustrup.

Machine learning enables computers to learn from data without being explicitly programmed.

Artificial Intelligence is the simulation of human intelligence by machines.

Recycling helps reduce waste and conserve natural resources.

The ozone layer protects life on Earth by blocking harmful UV radiation.

The lungs are spongy organs filled with tiny air sacs called alveoli.

The kidney filters waste from the blood and produces urine.

The digestive tract includes the mouth, esophagus, stomach, and intestines.

The nervous system includes the brain, spinal cord, and nerves.

The circulatory system transports oxygen and nutrients throughout the body.

Plagiarism is using someone else's work without proper attribution.

A haiku is a traditional form of Japanese poetry with 3 lines.

A biography is a written account of someone's life.

The water on Earth is constantly recycled through the water cycle.

Volcanoes are mountains that can erupt with lava and ash.

Tsunamis are large sea waves caused by underwater earthquakes.

Earthquakes are sudden movements of the Earth's crust.

Bacteria are single-celled microorganisms.

Viruses are infectious agents that require a host to reproduce.

... (you can add more manually)
"""

# ✅ Split into list
knowledge_paragraphs = [para.strip() for para in raw_knowledge.strip().split('\n\n') if para.strip()]
print(f"✅ Loaded {len(knowledge_paragraphs)} knowledge paragraphs.")

def smart_qa_bot(user_input, chat_history):
    # Step 1: Embed the question
    question_embedding = embedder.encode(user_input, convert_to_tensor=True)

    # Step 2: Embed all knowledge paragraphs
    para_embeddings = embedder.encode(knowledge_paragraphs, convert_to_tensor=True)

    # Step 3: Compute similarity and select top paragraph
    cosine_scores = util.pytorch_cos_sim(question_embedding, para_embeddings)
    top_idx = torch.argmax(cosine_scores)
    top_context = knowledge_paragraphs[top_idx]

    # Step 4: Feed question and top context to QA model
    result = qa_pipeline(question=user_input, context=top_context)
    answer = result['answer']

    # Step 5: Return answer to chat
    chat_history.append((user_input, answer))
    return "", chat_history

#  Build Gradio interface
with gr.Blocks() as demo:
    gr.Markdown("## 🤖 Smart Few-Shot Q&A Chatbot (with Semantic Search)")

    chatbot = gr.Chatbot(label="Smart Q&A Bot")
    msg_input = gr.Textbox(placeholder="Ask me a question...", label="Type your question here")
    clear_btn = gr.Button("🧹 Clear Chat")
    state = gr.State([])

    msg_input.submit(smart_qa_bot, [msg_input, state], [msg_input, chatbot])
    clear_btn.click(lambda: [], None, chatbot)

demo.launch()